enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi:
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 0.5 # degree -2.5
pitch_offset: -2 # degree 2
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.02 # s
low_speed_delay_time: 0.02 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 3
gain: 16.9
vid_pid: "2bdf:0001"

# 重投影误差: 0.1011px
camera_matrix: [1891.4701366623476, 0, 752.06633100587931, 0, 1899.258196389251, 470.8885120000956, 0, 0, 1]
distort_coeffs: [-0.059587850846567716, 0.15820702284203261, -0.0067151954384618408, 0.0021014060055056889, 0]

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 相机同理想情况的偏角: yaw0.78 pitch0.40 roll0.12 degree
# 标定板到世界坐标系原点的水平距离: 1.25 m
# 标定板同竖直摆放时的偏角: yaw-26.90 pitch13.41 roll-0.26 degree
R_camera2gimbal: [-0.013599691615852588, 0.0070809168032716398, 0.99988244759330536, -0.99990515548416758, 0.0020783336180901311, -0.013614718710075774, -0.0021744939954575822, -0.99997277020256781, 0.0070519805208648922]
t_camera2gimbal: [0.018030678721583572, 0.058580993689183875, 0.088135366162324258]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.002

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s

#####-----message参数-----#####
receive.gimbal: 1
receive.shoot: 2
send.gimbal: 1
send.shoot: 2
yaw: 1.0
pitch: 0.0
roll: 0.0
bullet_speed: 30.0
mode: 0
color: 0
serial_type: physical
