enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi:
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 2.5 # degree -2.5
pitch_offset: 0.3 # degree 2
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.015 # s
low_speed_delay_time: 0.015 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 2
gain: 16.9
vid_pid: "2bdf:0001"
camera_delay: 5500000

# 重投影误差: 0.1066px  // sentry
camera_matrix: [1763.4678070684445, 0, 669.88976606502445, 0, 1770.2118069420073, 512.63474238494814, 0, 0, 1]
distort_coeffs: [-0.053067037114795532, 0.074027285843277293, -0.0044522160748169557, -0.0032383055789270967, 0]

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 相机同理想情况的偏角: yaw2.19 pitch-0.55 roll-1.70 degree
# 标定板到世界坐标系原点的水平距离: 1.15 m
# 标定板同竖直摆放时的偏角: yaw22.17 pitch12.24 roll0.06 degree
#R_camera2gimbal: [  -0.03763286,  -0.01179213,   0.99922194,  -0.99777326,  -0.05533358,  -0.03823272, 0.05574044,  -0.99843336,  -0.00968414]
#R_camera2gimbal: [-0.037931419417050555, -0.010804204289149605, 0.99922193560324046, -0.99884217252020524, -0.029198862387887541, -0.03823271936928388, 0.02958921790323317, -0.99951523030163592, -0.0096841405887906074]
t_camera2gimbal: [-0.021693025751847075, 0, 0.112533666648000958]
camera_yaw: 0
camera_pitch: 20
camera_roll: 0
#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.002

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s

#####-----message参数-----#####
receive.gimbal: 1
receive.shoot: 2
send.gimbal: 1
send.shoot: 2
yaw: 1.0
pitch: 0.0
roll: 0.0
bullet_speed: 30.0
mode: 0
color: 0
serial_type: physical
